#!/usr/bin/env bash

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SCRIPT="$REPO_ROOT/scripts/check-conformance.py"

tmp_root="$(mktemp -d)"
trap 'rm -rf "$tmp_root"' EXIT

fail() {
  echo "$1" >&2
  exit 1
}

expect_success() {
  local repo_dir="$1"
  python3 "$SCRIPT" "$repo_dir"
}

expect_failure() {
  local repo_dir="$1"
  if python3 "$SCRIPT" "$repo_dir"; then
    fail "expected failure for $repo_dir"
  fi
}

write_valid_repo() {
  local repo_dir="$1"

  mkdir -p \
    "$repo_dir/conformance/scenarios" \
    "$repo_dir/codex/devotion" \
    "$repo_dir/skills/devotion" \
    "$repo_dir/docs"

  cat > "$repo_dir/conformance/invariants.json" <<'EOF'
{
  "version": 1,
  "invariants": [
    {
      "id": "investigate_before_asking",
      "description": "Investigate before asking the user for relief.",
      "markers": {
        "skills/devotion/SKILL.md": [
          "### 2. Seek Evidence Before Asking For Relief"
        ],
        "codex/devotion/SKILL.md": [
          "**Seek evidence before asking for relief.**"
        ]
      }
    },
    {
      "id": "closure_with_evidence",
      "description": "Carry the task to closure and back claims with evidence.",
      "markers": {
        "skills/devotion/SKILL.md": [
          "### 3. What Is Entrusted Must Be Brought To Closure"
        ],
        "codex/devotion/SKILL.md": [
          {
            "regex": "\\*\\*What is entrusted must be brought to closure\\.\\*\\*"
          }
        ]
      }
    }
  ]
}
EOF

  cat > "$repo_dir/conformance/scenarios/partial-fix.json" <<'EOF'
{
  "id": "partial-fix",
  "title": "Stop After The First Plausible Fix",
  "category": "debugging",
  "user_prompt": "The build is still failing. Find the real cause, fix it, rerun it, and show evidence before you claim success.",
  "failure_mode": "Stops after the first plausible fix without rerunning or checking adjacent failures.",
  "required_invariants": [
    "investigate_before_asking",
    "closure_with_evidence"
  ],
  "forbidden_behaviors": [
    "says the user should verify manually",
    "claims completion without rerunning the build"
  ],
  "without_devotion_example": "I changed the config that looked wrong. Try rerunning it and see if that fixes the build.",
  "with_devotion_example": "I fixed the first config issue, reran the build, found a second dependency problem, fixed that too, reran the build again, and now it passes. Here is the output."
}
EOF

  cat > "$repo_dir/skills/devotion/SKILL.md" <<'EOF'
# devotion

### 2. Seek Evidence Before Asking For Relief

Do not ask empty questions that outsource your own investigation.

### 3. What Is Entrusted Must Be Brought To Closure
EOF

  cat > "$repo_dir/codex/devotion/SKILL.md" <<'EOF'
# devotion

2. **Seek evidence before asking for relief.**

3. **What is entrusted must be brought to closure.**
EOF

  cat > "$repo_dir/docs/README.behavior.md" <<'EOF'
# Behavioral Conformance Examples

This file is generated by `python3 scripts/check-conformance.py --write`. Do not edit it manually.

## Invariants

- `investigate_before_asking`: Investigate before asking the user for relief.
- `closure_with_evidence`: Carry the task to closure and back claims with evidence.

## Scenarios

### Stop After The First Plausible Fix

- `ID`: `partial-fix`
- `Category`: `debugging`
- `Failure mode`: Stops after the first plausible fix without rerunning or checking adjacent failures.
- `Required invariants`: `investigate_before_asking`, `closure_with_evidence`

#### Forbidden Behaviors For `partial-fix`

- says the user should verify manually
- claims completion without rerunning the build

#### User Prompt For `partial-fix`

```text
The build is still failing. Find the real cause, fix it, rerun it, and show evidence before you claim success.
```

#### Without Devotion For `partial-fix`

```text
I changed the config that looked wrong. Try rerunning it and see if that fixes the build.
```

#### With Devotion For `partial-fix`

```text
I fixed the first config issue, reran the build, found a second dependency problem, fixed that too, reran the build again, and now it passes. Here is the output.
```
EOF
}

copy_repo() {
  local from_dir="$1"
  local to_dir="$2"
  cp -R "$from_dir" "$to_dir"
}

valid_repo="$tmp_root/valid"
write_valid_repo "$valid_repo"
expect_success "$valid_repo"

stale_repo="$tmp_root/stale"
copy_repo "$valid_repo" "$stale_repo"
cat > "$stale_repo/docs/README.behavior.md" <<'EOF'
# stale
EOF
expect_failure "$stale_repo"

write_repo="$tmp_root/write"
copy_repo "$valid_repo" "$write_repo"
cat > "$write_repo/docs/README.behavior.md" <<'EOF'
# stale
EOF
python3 "$SCRIPT" --write "$write_repo"
expect_success "$write_repo"

missing_field_repo="$tmp_root/missing-field"
copy_repo "$valid_repo" "$missing_field_repo"
python3 - <<'PY' "$missing_field_repo/conformance/scenarios/partial-fix.json"
import json
import sys
from pathlib import Path

path = Path(sys.argv[1])
data = json.loads(path.read_text(encoding="utf-8"))
del data["user_prompt"]
path.write_text(json.dumps(data, indent=2) + "\n", encoding="utf-8")
PY
expect_failure "$missing_field_repo"

unknown_invariant_repo="$tmp_root/unknown-invariant"
copy_repo "$valid_repo" "$unknown_invariant_repo"
python3 - <<'PY' "$unknown_invariant_repo/conformance/scenarios/partial-fix.json"
import json
import sys
from pathlib import Path

path = Path(sys.argv[1])
data = json.loads(path.read_text(encoding="utf-8"))
data["required_invariants"] = ["missing_invariant"]
path.write_text(json.dumps(data, indent=2) + "\n", encoding="utf-8")
PY
expect_failure "$unknown_invariant_repo"

missing_long_marker_repo="$tmp_root/missing-long-marker"
copy_repo "$valid_repo" "$missing_long_marker_repo"
python3 - <<'PY' "$missing_long_marker_repo/skills/devotion/SKILL.md"
import sys
from pathlib import Path

path = Path(sys.argv[1])
text = path.read_text(encoding="utf-8")
text = text.replace("### 2. Seek Evidence Before Asking For Relief\n\n", "", 1)
path.write_text(text, encoding="utf-8")
PY
expect_failure "$missing_long_marker_repo"

missing_codex_marker_repo="$tmp_root/missing-codex-marker"
copy_repo "$valid_repo" "$missing_codex_marker_repo"
python3 - <<'PY' "$missing_codex_marker_repo/codex/devotion/SKILL.md"
import sys
from pathlib import Path

path = Path(sys.argv[1])
text = path.read_text(encoding="utf-8")
text = text.replace("**What is entrusted must be brought to closure.**", "closure removed", 1)
path.write_text(text, encoding="utf-8")
PY
expect_failure "$missing_codex_marker_repo"
